### ISSUE TITLE
Files required for running ImageNet dataset

### ISSUE THREAD

**Issue by aparna-aketi** [YangtaoWANG95/TokenCut#12]
Hi @YangtaoWANG95,
I am a Ph.D. student from Purdue University. I am trying to run TokenCut with ImageNet but not able to figure out how to get the text files under ILSVRC/detection folder (i.e., train.txt, val.txt and wnids.txt). Can you please let me know where I can find files? Any help would be highly appreciated. 

Thanks,
Aparna

**Comment by YangtaoWANG95** [comment]
Hi Aparna,

I've uploaded the ImageNet/detection folder. Normally it should be ok. You could also find them in one of the baseline work: https://github.com/junsukchoe/ADL/tree/master/labels/ILSVRC. 
If you have any additional question, please let me know.

Best,
Yangtao

**Comment by aparna-aketi** [comment]
Thank you!
