### ISSUE TITLE
wants to improve the failed images comeout from this code

### ISSUE THREAD

**Issue by srilekhapanda** [YangtaoWANG95/TokenCut#13]
I have run this code for **unsupervised saliency detection** for ECSSD dataset where found some of the images are not generating the proper mask. 
Varying the tau and taking eigen vector without taking the absolute value getting some improved results. 

What could be the generalised solution for this type of images?

**Comment by XiSHEN0220** [comment]
Hi, @srilekhapanda 

Thanks for your interest in the project ! 

I think the adaptive tau might be something good to try. 
Maybe one naive solution is to build a list of tau as candidates and search for the one that produces the most separable eigenvector. 

To be honest, it is not evident to have a simple/general cutting strategy. If you find something that is elegant and works better, do not hesitate to make a pull request. 

Best,

**Comment by srilekhapanda** [comment]
Thanks for your response XiSHEN. I have one more question that for some of the images without taking the absolute value of the eigen vector getting improved results. Is it the right approach to do?

**Comment by XiSHEN0220** [comment]
We only leverage abs eigenvector to determine the seed, which for me, is reasonable to do.
Please refer to [this line](https://github.com/YangtaoWANG95/TokenCut/blob/master/object_discovery.py#L48) 

To get the bounding boxes, we still use the raw eigenvector. 
Please check [this part](https://github.com/YangtaoWANG95/TokenCut/blob/master/object_discovery.py#L44-L46)

**Comment by srilekhapanda** [comment]
Okay Xishen thank you again for clarification. Have a good day.
