### ISSUE TITLE
Why in this paper we are using NCut given the edge weights are all non-negative?

### ISSUE THREAD

**Issue by Helicopt** [YangtaoWANG95/TokenCut#14]
In the paper, the graph is constructed in a way that all edge weights are either 1 or eps (almost zero), making the NCut energy's optimal value is 0. Then the problem has a trivial solution of A=all nodes and B=empty set. Actually we have a lot of trivial solutions like A=a connected component in the graph and B=the rest nodes. In this way how can we tell which solution is desired? And because the graph is collapsed, the problem becomes very easy and it doesn't need the relaxed version of the NCut at all. 

If I have any misunderstandings, could you please explain that to me?

**Comment by YangtaoWANG95** [comment]
Hi,
Thank you for your interest in our project!
In fact, we find that most graphs are connected graph, as the features from DINO contain already positional embedding, which enforces connections between neighbor patches. Adding eps enforces a connected graph (w.o it, the performance drops a 0.1-0.3%  on VOC07 and VOC12). In such case, the optical solution is the 2nd smallest eigen vector. 
Hope my answer helps.
