### ISSUE TITLE
Support returning bounding box coordinates

### ISSUE THREAD

**Issue by lextoumbourou** [YangtaoWANG95/TokenCut#4]
Hi there,

Amazing work with TokenCut! I'm impressed at how well this appears to work on the dataset I'm playing with.

It would be great if there was a convenient method for returning bounding box predictions, instead of just images annotated with the bounding boxes. If that already exists, please point me in the right direction.

**Comment by XiSHEN0220** [comment]
Hi, 

Thanks for your interest in our work! 

You can try [these commands](https://github.com/YangtaoWANG95/TokenCut#31-detecting-an-object-in-one-image) which will run TokenCut on a single image.

The bounding box prediction is [the first output of the ncut function](https://github.com/YangtaoWANG95/TokenCut/blob/master/main_tokencut.py#L270)

Hope this is what you want. 

Best, 

Xi

**Comment by XiSHEN0220** [comment]
I close the issue. 
If you have any other questions, feel free to re-open it.
