### ISSUE TITLE
CVPR2022 call for demos

### ISSUE THREAD

**Issue by AK391** [YangtaoWANG95/TokenCut#5]
Hi, there is a call for demos this year for cvpr 2022

https://cvpr2022.thecvf.com/call-demos

where a demo can be added to the Hugging Face organization here: https://huggingface.co/cvpr

As there is already a Gradio demo for Tokencut on Hugging Face https://huggingface.co/spaces/akhaliq/TokenCut, would you be interested in submitting a demo for this?

**Comment by YangtaoWANG95** [comment]
Hi AK,

Thank you for your nice suggestion. However, it seems that the the paper registration deadline Round 2 is March 18, 2022, thus we might not be able to submit our demo for this event.  If you have other suggestions, don't hesitate to contact us. 

Best,
Yangtao
