### ISSUE TITLE
Results about unsupervised salient object detection

### ISSUE THREAD

**Issue by moothes** [YangtaoWANG95/TokenCut#6]
I notice that the reported results of DeepUSPS are significantly lower than other methods, even traditional HS.
I used to test the performance of this method and reported much better performance than the scores reported in this paper. 
In addition, [1] can also prove that DeepUSPS should not get such low scores. 

[1] A Causal Debiasing Framework for Unsupervised Salient Object Detection. AAAI 2022.

**Comment by XiSHEN0220** [comment]
Hi, 

Thanks for noticing that. The difference comes from a fair comparison to DeepUSPS.

In fact, the benchmark is taken from BigBiGAN[58]. 

In [58], it precises that:  "_While there are a large number of papers on unsupervised deep saliency detection, all of them employ pretrained supervised models in their training protocols....To compare with deep saliency detection
models, we also add DeepUSPS (Nguyen et al., 2019) to the list of baselines. However, to perform a fair comparison,
we train the DeepUSPS model without pretraining on the CityScapes dataset._ "

@YangtaoWANG95 Might be good to update the paper.

We need to 
1. add citation [58] in table 3 and explain that some results are taken from [58] 
2. precise why DeepUSPS is worse.

**Comment by moothes** [comment]
Thanks for your quick reply!
So DeepUSPS is pretrained with randomly initialized weights? Or other unsupervised pretrained weights?

**Comment by XiSHEN0220** [comment]
Hi, 
As there are no details about the initialization in [58], I would guess it is pre-trained with randomly initialized weights (not sure).

**Comment by moothes** [comment]
Ok, I get it.
Thanks!
