### ISSUE TITLE
how to prepare the imagenet dataset 

### ISSUE THREAD

**Issue by gazelxu** [YangtaoWANG95/TokenCut#7]
Sincerely thanks to this greate work!
I get images and boxes annotations from imagenet official website. However, how to prepare the imagenet dataset as follows?
 ./datasets/ImageNet/
                    ├── ILSVRC
                        ├── Annoations
                        ├── Data
                        ├── Detection
                        ├── ImageSets
                    ├── LOC_synset_mapping.txt
                    ├── LOC_val_solution.csv

                        ...

**Comment by aparna-aketi** [comment]
Hi @gazelxu, Did you figure out how to prepare imagenet?
